name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    
    steps:
      - uses: ./action-a
      - name: my-step
        run: echo "Hello World!"


# name: A workflow for my Hello World file
# on: push
# jobs:
#   build:
#     name: Hello world action
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v1
#       - uses: ./action-a
#         with:
#           MY_NAME: "Mona"
